

---
- hosts: all
  remote_user: root

  tasks:
    - name: Install required packages
      apt: 
        update_cache: yes
        force_apt_get: yes
        pkg:
        - python3
        - python3-pip
        # - ufw
        - nginx
        - postgresql-client
    - name: Install gunicorn, django and dependencies
      pip:
        name: 
        - psycopg2-binary
        - django
        - gunicorn
        state: present
    - systemd:
        name: nginx
        state: stopped
        enabled: true
    - systemd:
        name: gunicorn
        state: stopped
        enabled: true
      register: result_systemd_stop
      failed_when: "result_systemd_stop is failed and 'Could not find the requested service' not in result_systemd_stop.msg"
    - name: copy django project
      copy:
        src: diary_project
        dest: /opt/
        owner: www-data
        group: www-data
        mode: 0644
      notify:
    - replace:
        path: /opt/diary_project/settings.py
        regexp: 'ALLOWED_HOSTS.*'
        replace: "ALLOWED_HOSTS = ['{{ ansible_default_ipv4.address }}']"
    - name: copy django app
      copy:
        src: diary_app
        dest: /opt/
        owner: www-data
        group: www-data
        mode: 0644
      notify:
    - name: copy static files
      copy:
        src: static
        dest: /opt/
        owner: www-data
        group: www-data
        mode: 0644
      notify:
    - name: copy systemd gunicorn.service
      copy:
        src: ansible-files/gunicorn.service
        dest: /etc/systemd/system/gunicorn.service
    - name: copy nginx.conf
      copy:
        src: ansible-files/nginx.conf
        dest: /etc/nginx/nginx.conf
    - replace:
        path: /etc/nginx/nginx.conf
        regexp: 'server_name.*'
        replace: "server_name {{ ansible_default_ipv4.address }};"
    - name: copy nginx https key
      copy:
        src: ansible-files/nginx_https.key
        dest: /etc/ssl/
        owner: www-data
        group: www-data
        mode: 0600
    - name: copy nginx https crt
      copy:
        src: ansible-files/nginx_https.crt
        dest: /etc/ssl/
        owner: www-data
        group: www-data
        mode: 0600
    - systemd:
        daemon_reload: true
    - systemd:
        name: gunicorn
        state: started
        enabled: true
    - systemd:
        name: nginx
        state: started
        enabled: true